@echo ON

cmake -S . -B build -G Ninja ^
  -DCMAKE_BUILD_TYPE:STRING=Release ^
  -DCMAKE_INSTALL_PREFIX:PATH=%LIBRARY_PREFIX% ^
  -DCMAKE_PREFIX_PATH:PATH=%LIBRARY_PREFIX% ^
  -DCMAKE_INSTALL_LIBDIR:PATH=%LIBRARY_LIB% ^
  -DCMAKE_INSTALL_INCLUDEDIR:PATH=%LIBRARY_INC%
cmake --build build
cmake --install build
